steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - '-c'
      - >
        docker build -f ./RefundSystem/RefundSystem.API/Dockerfile ./RefundSystem --force-rm -t
        us-central1-docker.pkg.dev/refundprojeckt-489807/test/refund-system-api:$COMMIT_SHA &&
        docker push us-central1-docker.pkg.dev/refundprojeckt-489807/test/refund-system-api:$COMMIT_SHA
    entrypoint: bash
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - refund-system-api  
      - --image=us-central1-docker.pkg.dev/refundprojeckt-489807/test/refund-system-api:$COMMIT_SHA
      - --region=me-west1
      - --platform=managed
options:
  logging: CLOUD_LOGGING_ONLY