// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefundSystem.Data.Context;

#nullable disable

namespace RefundSystem.Data.Migrations
{
    [DbContext(typeof(RefundSystemDbContext))]
    partial class RefundSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RefundSystem.Core.Entities.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TotalBudget")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("UsedBudget")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Budgets__3214EC076E605BA9");

                    b.HasIndex(new[] { "Year", "Month" }, "UQ_Budget")
                        .IsUnique();

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("RefundSystem.Core.Entities.Citizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Citizens__3214EC0759D72142");

                    b.HasIndex(new[] { "IdentityNumber" }, "UQ__Citizens__6354A73F6DD81155")
                        .IsUnique();

                    b.ToTable("Citizens");
                });

            modelBuilder.Entity("RefundSystem.Core.Entities.Clerk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("Id")
                        .HasName("PK__Clerks__3214EC07D29DFD59");

                    b.HasIndex(new[] { "IdentityNumber" }, "IX_Clerks_IdentityNumber")
                        .IsUnique();

                    b.ToTable("Clerks");
                });

            modelBuilder.Entity("RefundSystem.Core.Entities.MonthlyIncome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint");

                    b.Property<int>("TaxYear")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__MonthlyI__3214EC0794180316");

                    b.HasIndex(new[] { "CitizenId", "TaxYear", "Month" }, "UQ_MonthlyIncome")
                        .IsUnique();

                    b.ToTable("MonthlyIncomes");
                });

            modelBuilder.Entity("RefundSystem.Core.Entities.RefundRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ApprovedAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal?>("CalculatedAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime?>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CitizenId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TaxYear")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__RefundRe__3214EC074AC54EF6");

                    b.HasIndex("StatusId");

                    b.HasIndex(new[] { "CitizenId", "TaxYear" }, "UQ_RefundRequests")
                        .IsUnique();

                    b.ToTable("RefundRequests");
                });

            modelBuilder.Entity("RefundSystem.Core.Entities.RequestStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__RequestS__3214EC07FC1C8A09");

                    b.ToTable("RequestStatuses");
                });

            modelBuilder.Entity("RefundSystem.Core.ReadModels.PendingRequestReadModel", b =>
                {
                    b.Property<decimal?>("CalculatedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxYear")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView(null, (string)null);
                });

            modelBuilder.Entity("RefundSystem.Core.Entities.MonthlyIncome", b =>
                {
                    b.HasOne("RefundSystem.Core.Entities.Citizen", "Citizen")
                        .WithMany("MonthlyIncomes")
                        .HasForeignKey("CitizenId")
                        .IsRequired()
                        .HasConstraintName("FK_MonthlyIncomes_Citizens");

                    b.Navigation("Citizen");
                });

            modelBuilder.Entity("RefundSystem.Core.Entities.RefundRequest", b =>
                {
                    b.HasOne("RefundSystem.Core.Entities.Citizen", "Citizen")
                        .WithMany("RefundRequests")
                        .HasForeignKey("CitizenId")
                        .IsRequired()
                        .HasConstraintName("FK_RefundRequests_Citizens");

                    b.HasOne("RefundSystem.Core.Entities.RequestStatus", "Status")
                        .WithMany("RefundRequests")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_RefundRequests_Status");

                    b.Navigation("Citizen");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("RefundSystem.Core.Entities.Citizen", b =>
                {
                    b.Navigation("MonthlyIncomes");

                    b.Navigation("RefundRequests");
                });

            modelBuilder.Entity("RefundSystem.Core.Entities.RequestStatus", b =>
                {
                    b.Navigation("RefundRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
